### ISSUE TITLE
Information about CPU usage

### ISSUE THREAD

**Issue by mfoglio** [LukasBommes/mv-extractor#2]
Does this tool decode the video or does it retrieve the motion vectors without decoding it? I am looking for a solution with low CPU usage. I looked at the code and it seems the entire frame is decoded, however, I am not a `C++` expert. Thank you.

**Comment by LukasBommes** [comment]
Dear mfoglio,

excuse the belated reply.
The tool indeed decodes the video frame entirely. It should be possible to obtain the motion vectors and only partially decode the frame. But this would require changing most of `video_cap.cpp`. If you want to implement this change, I recommend asking on the FFMPEG mailing list on how to obtain motion vectors and only partially decode the frame. The community over there was quite willing to answer questions when I worked on this project.

Best regards,
Lukas
