### ISSUE TITLE
About the new docker

### ISSUE THREAD

**Issue by JXH-SHU** [LukasBommes/mv-extractor#22]
Thank you for developing this great tool for motion extraction.

I tried to use the docker you provided, but the codes reported an error. The error message is "No module named 'mvextractor'". Looking forward to your reply。

**Comment by LukasBommes** [comment]
Have you tried the import as follows?
```
from mvextractor.videocap import VideoCap
```
With the new Docker image, I changed the directory structure of the package and now the import statement is different.

**Comment by JXH-SHU** [comment]
Thank you for your reply. Yes, I used the updated codes ("from mvextractor.videocap import VideoCap"), and it reported the error ("No module named 'mvextractor'").

**Comment by LukasBommes** [comment]
Okay. Does the error occur when importing in your own code or when running the "extract_mvs" script as mentioned in the readme?

Also, have you tried the PyPI package?

**Comment by JXH-SHU** [comment]
Thank you for your reply. I tried to install the tool using PyPI package, but it failed. Finally, I use the last version of the tool for my tests.

**Comment by JXH-SHU** [comment]
What I tried to install was the readily built Docker you provided. According to your instructions, I successfully copied the docker you provided, but it couldn't test it successfully.

I am on Ubuntu 16.04 x86_64.

**Comment by LukasBommes** [comment]
Could you send the exact commands you tried to execute? E.g. how did you clone the repo and which command did you run in the Docker container? 

And can you post the exact error traceback that is being thrown?

The tool should be compatible with ubuntu 16.04 x86_64.

**Comment by zara6697** [comment]
Dear all,
Thanks for the library. I use this code in docker. when I run the test file, I got error "File "/home/video_cap/tests/tests.py", line 4, in <module>
    from mvextractor.videocap import VideoCap
ModuleNotFoundError: No module named 'mvextractor'"
Could you help me how to solve it?
Best regards,

**Comment by LukasBommes** [comment]
@ZaraNaSha Could you please create a new issue with more details, e.g. your the exact commands that you executed?
