### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by SoftologyPro** [LukasBommes/mv-extractor#30]
pip install motion-vector-extractor
ERROR: Could not find a version that satisfies the requirement motion-vector-extractor (from versions: none)
ERROR: No matching distribution found for motion-vector-extractor

**Comment by KoalaAndyZheng** [comment]
I met the same problem, have you solved it?

**Comment by jianlong-yuan** [comment]
same error on Centos 7

**Comment by XDUWQ** [comment]
```
git clone https://github.com/LukasBommes/mv-extractor.git
cd mv-extractor/
pip install .
```

**Comment by XDUWQ** [comment]
![image](https://github.com/LukasBommes/mv-extractor/assets/37444407/de7e6fa1-b4e1-4a86-a180-33b6436c79ab)
I found that it seems to only support Python versions 3.8 and above. After updating the Python version, the installation can be completed smoothly

**Comment by XDUWQ** [comment]
https://pypi.org/project/motion-vector-extractor/#files

**Comment by 1933874502** [comment]
> ![image](https://user-images.githubusercontent.com/37444407/257096123-de7e6fa1-b4e1-4a86-a180-33b6436c79ab.png) I found that it seems to only support Python versions 3.8 and above. After updating the Python version, the installation can be completed smoothly

My python version is 3.10 and I still get this error

**Comment by YujieOuO** [comment]
can not support CentOS？i get the same error

**Comment by ashleycolton** [comment]
> pip install motion-vector-extractor ERROR: Could not find a version that satisfies the requirement motion-vector-extractor (from versions: none) ERROR: No matching distribution found for motion-vector-extractor

exactly this issue, python version 3.8
is it only for linux?

**Comment by LukasBommes** [comment]
Hey guys,
sorry for never responding to this issue. As you can see from the GitHub workflow (https://github.com/LukasBommes/mv-extractor/blob/master/.github/workflows/build.yml), I am only building the Python package for Ubuntu and Python versions 3.8 to 3.10. If a project is not a pure Python library, the Python wheel resulting from the build is specific to platform and Python version. Hence, one would have to build the wheel for a matrix of all platforms and Python versions, which is challenging to maintain. Instead, I am shipping the Docker image which should allow you to run mv-extractor on CentOS (via Docker).
