### ISSUE TITLE
Limit the maximal number of threads

### ISSUE THREAD

**Issue by luowyang** [LukasBommes/mv-extractor#32]
`VideoCap::open()` sets the number of threads to whatever is returned by `std::thread::hardware_concurrency()` in [this line](https://github.com/LukasBommes/mv-extractor/blob/995ed82d38f2081f2a41fb69e570295ffc1fc2d4/src/mvextractor/video_cap.cpp#L115). However, on machines with many cores the number of threads will exceed the maximum recommended by FFmpeg (which is 16 as defined [here](http://ffmpeg.org/doxygen/trunk/pthread__internal_8h_source.html#l00026)). This may degrade performance, and FFmpeg will issue an annoying warning says "Using a thread count greater than 16 is not recommended". It may be wiser to follow the recommendation and limit the number of threads to no larger than 16.

**Comment by LukasBommes** [comment]
Thanks for the contribution @luowyang. I will include this with the next release.
