### ISSUE TITLE
Updating opencv dependency

### ISSUE THREAD

**Issue by aeilkol** [LukasBommes/mv-extractor#36]
Hello,

I am using this package in a project to synchronize multiple different camera streams, which I then need to process. In this processing, I have packages that require opencv versions >= 4.6, which are in conflict with the requirements of this package. Would it be possible to update the package dependencies to allow using newer opencv versions?

Thank you very much for the great work either way!

**Comment by LukasBommes** [comment]
Thanks for the request @aeilkol!
I am working on the next release where OpenCV 4.10.0 will be used.

**Comment by LukasBommes** [comment]
Should be resolved in release 1.1.0. Feel free to reopen if there are still issues.
